### PR TITLE
feat: add option to create readonly arrays

### PR DESCRIPTION
**Pull request by aszenz**

### CODE REVIEW

**Review by aszenz — COMMENTED** [review]
Relates to #26

**Comment by michaljanocko** [comment]
Can't one do just this?

```ts
D.array(D.string) as Decoder<ReadonlyArray<string>>
```

I'm asking because the type signature gets compiled away so we just end up with the same function as `array`.

**Comment by aszenz** [comment]
> Can't one do just this?
> 
> ```ts
> D.array(D.string) as Decoder<ReadonlyArray<string>>
> ```
> 
> I'm asking because the type signature gets compiled away so we just end up with the same function as `array`.

Would it be possible to do this without repeating the inferred type of T(array<string>). I would like it to be inferred and then modified to readonly

**Comment by michaljanocko** [comment]
It isn't really modified at runtime, only at compile-time. You could create something like this:

```ts
const readonlyArrayDecoder = (decoder: Decoder<D>) => D.array(decoder) as Decoder<ReadonlyArray<D>>

const objectDecoder = D.object({
  required: {
    somethingThatShouldBeAReadonlyArray: readonlyArrayDecoder(D.string)
  }
})
```

You would have to do this only once in your project and then reuse it. Since pretty much compiles away, I don't really feel like including this in the library.

**Comment by aszenz** [comment]
> You would have to do this only once in your project and then reuse it. Since pretty much compiles away, I don't really feel like including this in the library.

Ok, makes sense, actually the same is also for readonly objects, so we can close this

**Pull request closed without merging**
